name: Docker
on: [push]
jobs:
  builder:
    name: Builder
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: latest=false,suffix=-builder
          tags: type=ref,event=branch
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          cache-to: type=gha
          cache-from: type=gha
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    outputs:
      tag: ${{ steps.meta.outputs.tags }}
  test:
    name: Test
    needs: builder
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker run \
            --entrypoint '/bin/sh' ${{ needs.builder.outputs.tag }} '-c' \
            'make test'
  deploy:
    name: Deploy
    needs: builder
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: latest=false
          tags: type=edge
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          file: ./Dockerfile-deploy
          build-args: BUILDER_TAG=${{ needs.builder.outputs.tag }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  doc:
    name: Doc
    needs: builder
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker run \
            -v ${PWD}/output:/output \
            --entrypoint '/bin/sh' ${{ needs.builder.outputs.tag }} '-c' \
            'make doc && cp -r _build/default/_doc/_html /output/'
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: "./output/_html"
