name: Docker
on: [push]
jobs:
  test:
    name: Test/Deploy/Doc
    runs-on: ubuntu-latest
    steps:
      - name: Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: OPAM
        uses: docker/build-push-action@v2
        with:
          target: opam
          push: false
          cache-from: type=gha
          cache-to: type=gha
      - name: Test
        uses: docker/build-push-action@v2
        with:
          target: test
          push: false
      - name: Deploy
        uses: docker/build-push-action@v2
        with:
          target: deploy
          push: false
      - name: Doc
        uses: docker/build-push-action@v2
        with:
          target: doc
          tags: cooltt-doc
          load: true
          push: false
      - name: Copy Doc
        run: docker run -v ${PWD}/output:/output cooltt-doc /output
      - name: Upload Doc
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./output/_html"
