name: Docker
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - uses: docker/build-push-action@v2
        with:
          target: test
          push: false
          cache-from: type=gha
          cache-to: type=gha
  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - uses: docker/build-push-action@v2
        with:
          target: deploy
          push: false
          cache-from: type=gha
          cache-to: type=gha
  doc:
    name: Doc
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - uses: docker/build-push-action@v2
        with:
          target: doc
          tags: cooltt-doc
          load: true
          push: false
          cache-from: type=gha
          cache-to: type=gha
      - name: Copy Doc
        run: docker run -v ${PWD}/output:/output cooltt-doc /output
      - name: Upload Doc
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./output/_html"
