name: Docker/Base
on:
  workflow_dispatch:
  schedule:
    - cron: "2 6 * * *"
jobs:
  base:
    name: Base
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          # The other steps will assume that there's only one tag in
          # steps.meta.outputs.tags, and that's why `latest=false` and
          # there is only one line in `tags`.
          flavor: latest=false
          tags: type=raw,value=base
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          target: base
          cache-to: type=gha
          cache-from: type=gha
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
