name: Docker
on: push
jobs:
  builder:
    name: Builder
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          # The other steps will assume that there's only one tag in
          # steps.meta.outputs.tags, and that's why `latest=false` and
          # there is only one line in `tags`.
          flavor: latest=false,prefix=builder-
          tags: type=ref,event=branch
      - uses: docker/metadata-action@v3
        id: meta-base
        with:
          images: ghcr.io/${{ github.repository }}
          # The other steps will assume that there's only one tag in
          # steps.meta.outputs.tags, and that's why `latest=false` and
          # there is only one line in `tags`.
          flavor: latest=false
          tags: type=raw,value=base
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          build-args: BASE_TAG=${{ steps.meta-base.outputs.tags }}
          cache-to: type=gha
          cache-from: type=gha
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    outputs:
      tag: ${{ steps.meta.outputs.tags }}
  test:
    name: Test
    needs: builder
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker run \
            --entrypoint 'make' ${{ needs.builder.outputs.tag }} 'test'
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Deploy
    needs: builder
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: latest=false
          tags: type=edge
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          file: ./Dockerfile-deploy
          build-args: BUILDER_TAG=${{ needs.builder.outputs.tag }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  doc:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Doc
    needs: builder
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker run \
            -v ${PWD}/output:/output \
            --entrypoint '/bin/sh' ${{ needs.builder.outputs.tag }} '-c' \
            'make doc && cp -r _build/default/_doc/_html /output/'
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: "./output/_html"
